version: "3.8"

services:
    backend:
        build:
            context: .
        tty: true
        ports:
            - 3000:3000
        restart: always
        environment:
            - NODE_ENV=staging
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=123456
            - POSTGRESQL_HOST=database
            - POSTGRESQL_PORT=5432
            - POSTGRESQL_PASSWORD=martectuser1234
            - POSTGRESQL_USERNAME=martectuser
            - POSTGRESQL_DATABASE=martect_database
        links:
            - database
            - redis
        depends_on:
            - database
            - redis
        networks:
            - martect-system-network
    database:
        image: 'bitnami/postgresql:11'
        ports:
            - 5432:5432
        volumes:
            - postgresql_data:/bitnami/postgresql
            - ./database:/docker-entrypoint-initdb.d/create-db.sql
        environment:
            - POSTGRESQL_PASSWORD=martectuser1234
            - POSTGRESQL_USERNAME=martectuser
            - POSTGRESQL_DATABASE=martect_database
            - POSTGRESQL_POSTGRES_PASSWORD=martectuser1234
        networks:
            - martect-system-network
    redis:
        image: docker.io/bitnami/redis:6.2
        restart: always
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            #- ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PASSWORD=123456
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - 63790:6379
        volumes:
            - 'redis_data:/bitnami/redis/data'
        networks:
            - martect-system-network
volumes:
    redis_data:
        driver: local
    postgresql_data:
        driver: local
networks:
    martect-system-network: